// M3 playable vertical slice. Workflow({ scriptPath: 'tools/workflows/w3-client.js' })
export const meta = {
  name: 'w3-client',
  description: 'WarMechForge M3: playable hex client vs random bot on Pages (record sheet, heat, movement/firing UI, How to Play)',
  phases: [
    { title: 'Core', detail: 'store, presentation director, bot driver, client contract (copied from Whirr)' },
    { title: 'Build', detail: 'hex board + mech kit + interaction; record sheet/heat/prompts/dice/feed; start screen + How to Play' },
    { title: 'Ship', detail: 'integrate, play it, Playwright full game, screenshots, push, Pages' },
  ],
}

const ROOT = 'C:/Users/antho/OneDrive/Documents/WarMechForge/warmechforge'
const WHIRR = 'C:/Users/antho/OneDrive/Documents/WarMForge/whirr-machine'
const ATTR = 'Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>'
const RESULT = { type: 'object', properties: { ok: { type: 'boolean' }, summary: { type: 'string' }, files: { type: 'array', items: { type: 'string' } }, issues: { type: 'array', items: { type: 'string' } } }, required: ['ok', 'summary', 'files', 'issues'] }

const COMMON = `Project root: ${ROOT} (git repo, branch main, remote github.com/dragoonant/warmechforge, Pages https://dragoonant.github.io/warmechforge/). Windows; absolute paths, the cwd resets. Run long commands in the FOREGROUND. Orient from ${ROOT}/STATUS.md, then docs/spec/50-client.md and only the other spec sections named. The engine (src/engine/index.ts: createGame/step/legalActions/query.*/describe.*) and data (src/data loadBundle) exist; the client is the ONLY caller of engine.step, via the zustand store. The engine owns every number the UI shows (to-hit target + modifier breakdown + odds, LOS verdict, arcs, MP costs, reachable set, heat projection, PSR targets): never compute rules numbers in the client. Do not edit src/engine or src/data (report needed engine changes in issues). The sibling game Whirr Machine (${WHIRR}/src/client) already solved store, presentation director, bot driver, dice tray, camera, frame-rate and test hooks: COPY its files and adapt them rather than writing from scratch (it is our own code). Its game rules are Warmachine: do not copy rules logic. Game is BattleTech Classic on a flat-topped hex map; 'Mechs face hexsides. IP rule: all UI copy in our own words; never the BattleTech logo; never Catalyst record-sheet layout (our own layout); UI and start screen carry "Unofficial fan project, not affiliated with or endorsed by Catalyst Game Labs, Topps or Microsoft." Visual theme: dark charcoal and gold (--bg:#14161a --fg:#e8e6e1 --card:#1e2127 --accent:#c9a227, heat red #d0402b, hazard amber #e08a1e). Concurrent agents share this tree: touch only files you own, never edit STATUS.md/package.json, never git commit or npm install unless told. Final output is raw JSON for an orchestrator.`

phase('Core')
const core = await agent(`${COMMON}
Build the client core and FREEZE its contract for the three parallel agents that come next. You own src/client/store/**, src/client/presentation/**, src/client/bot/**, src/client/contract.ts, and may npm install if truly needed. Start by copying the matching Whirr files (${WHIRR}/src/client/{store,presentation,bot,contract.ts}) and adapting them.
- zustand game store: new game from setup options (mission, forces, who is human, bot tier), dispatch(action) -> engine.step, rejection messages, selected unit, UI mode (select / move / fire / physical / measure / los), hovered hex, autosave each turn to localStorage with Continue.
- presentation director + presented store: events become timed beats (move tweens hex by hex with facing turns, torso twist, weapon fire, dice rolls, damage pops per location, crit banners, falls, shutdown, destruction, phase banners with narration pauses 2.4 s per phase / 1.6 s per turn scaled by speed); the UI renders presented state at the cursor; any click skips.
- bot driver: the random bot (src/ai/random.ts) answers bot-owned decisions only when presentation is idle; 5 s watchdog force-answers.
- src/client/contract.ts: typed selectors and actions the board/HUD/start agents will use (one-line comments), incl. selectors for the engine queries (reachable set for the selected unit and mode, attack preview per weapon/target, LOS verdict, heat projection), plus test hooks: ?test=1 exposes window.__game {state, pending, legal, dispatch, skipAll, speed, presentedIdle}; ?scenario=&control=bot,bot&seed= skips the start screen.
- tests/client/store.test.ts: a full bot-vs-bot game runs through the store headless.
Run typecheck and your tests. Return JSON: ok, summary, files, issues.`, { label: 'client-core', phase: 'Core', schema: RESULT, effort: 'high' })

phase('Build')
const PARTS = [
  { key: 'board', own: 'src/client/board/**, src/client/figures/**, src/client/interaction/**, src/client/vfx/**, public/assets/models/manifest.json, docs/spec/30-figures.md', task: `R3F battlefield (spec 50-client.md board sections, 70-maps.md, 30-figures.md): flat-topped hex board from map data (instanced hex tiles, stepped elevation terraces at LEVEL_HEIGHT, light/heavy woods as low stylised tree clumps capped below 'Mech shoulder height, rough as rock scatter, water as translucent depth-tinted hexes), a desert ground look, thin toggleable hex lines, XXYY label on hover. Procedural 'Mech kit (30-figures.md): separate nodes for legs, upper body (torso+cockpit, rotates for torso twist), left/right arm (hideable when destroyed), sized by weight class, force colours (two-tone), selection ring, facing arrow, status visuals (prone = tipped on side, shutdown = slumped + lights out, heat glow emissive orange 10+ red 20+, smoke from damaged locations, wreck). Interaction: click unit to select; in move mode show the engine's reachable set as hex highlights (walk green, run amber, jump blue), hover a hex to preview the path with MP spent and facing arrows, click hex then choose final facing (6 arrow buttons or wheel) then confirm; in fire mode draw firing arcs (front/sides/rear and twist preview), LOS line to hovered enemy coloured by verdict with reasons, weapon range rings; ruler tool (hex count + range band). GLB figures: public/assets/models/bt-solitaire.glb and bt-regent.glb exist (owner gate pending) and are already split into nodes base, lower, upper (pivot at the hip; rotate about Y for torso twist), armL/armR (children of upper, origin at the shoulder; hide when the arm is destroyed); front faces +z, the figure's left is +x; heights light 0.75 / assault 1.0 world units. Build the Whirr-style loader (copy ${WHIRR}/src/client/figures/{glbLoader,glbModels,glbPaint}.ts, never suspend, procedural kit shows meanwhile) with public/assets/models/manifest.json listing enabled slugs, a GLB_SLUG_BY_MODEL map (chassis -> bt-<chassis>), the hue-band army painter for force colours, and a ?gallery turntable showing every figure with twist and arm-loss toggles; 'Mechs without a GLB use the procedural kit. Update docs/spec/30-figures.md node names to match these GLBs (you own it for this). VFX: laser beams, PPC bolt, autocannon tracers, missile trails, explosions, jump-jet flames (simple, cheap). Camera: copy Whirr Camera.tsx (right-drag orbit, middle/WASD pan, wheel zoom, left-click reserved), transitions <=600 ms. Performance: demand frameloop, dpr cap, shared geometry. Invisible DOM proxies data-testid="mech-<id>" with data-hex and data-facing; data-testid="hex-<XXYY>" proxies for clickable highlighted hexes.` },
  { key: 'hud', own: 'src/client/ui/** (except src/client/ui/start/** and src/client/ui/help/**), src/client/dice/**', task: `In-game HUD (spec 50-client.md): top bar with turn, phase, initiative order and whose decision it is; RECORD SHEET panel for the selected unit (our own layout): armor/internal paper-doll front and rear filled by damage, weapons table (location, heat, damage, min/short/medium/long, ammo), crit slots per location with destroyed slots struck through, ammo bins, heat scale with current heat and threshold effects highlighted, pilot hits and consciousness targets, MP walk/run/jump current vs base; a compact enemy card on hover. Decision panel driven by the engine's pending decision: movement mode buttons (stand still / walk / run / jump / stand up) with MP shown; ranged attack panel: torso twist buttons, target pick, per-weapon checkboxes showing the engine's to-hit target, odds and modifier breakdown, live heat total and end-of-turn heat projection with warnings (shutdown/ammo risk), confirm button with a self-explaining prompt e.g. "Fire ER PPC at Rakshasa? Target 8 (Gunnery 4, medium range +2, you walked +1, target moved 5 hexes +2, light woods +1) = 72%. +15 heat -> 9 after sinks."; physical attack panel; PSR/consciousness/shutdown prompts that name the roll, target and why. Dice tray on the right rail (copy Whirr dice/; every roll purpose the engine emits has a renderer, enforced by a test; target read from state, not events). Event feed with full breakdowns (to-hit math, location, armor/internal before -> after, crits, transfers, heat). Game-over screen with cause, damage per side and Play again. Side rails collapse with [ and ]. data-testid scheme <area>-<element>[-id].` },
  { key: 'start', own: 'src/client/ui/start/**, src/client/ui/help/**, src/client/App.tsx, src/main.tsx, index.html', task: `Start screen titled "WarMechForge" with the unofficial-fan-project notice, fitting one screen: mission (Intro mission, Skirmish), your force vs enemy force with the 'Mechs listed (name, variant, tonnage, BV; "(stock)" label where data says so), opponent (random bot now; AI tiers later), seed, speed, Continue (if autosave), Start, and a prominent "How to Play" button. HOW TO PLAY (must be good, our own words, tabbed, skimmable): Goal; Your 'Mech (record sheet: armor, internal structure, crit slots, heat sinks, pilot gunnery/piloting); Turn sequence (initiative, movement, ranged attacks, physical attacks, heat, end); Moving (walk/run/jump, MP costs, facing, terrain, target movement modifier, prone and standing); Shooting (arcs, torso twist, LOS and woods, range bands, to-hit modifiers, hit locations, clusters); Damage (armor -> internal -> transfer, critical hits, ammo explosions); Heat (the heat scale, shutdown); Piloting rolls and falls; Physical attacks; Controls (mouse/keyboard, camera, skip animations); plus "Your first turn" walkthrough. Contextual coach line at the bottom saying what to do next for the current pending decision, dismissible, remembered in localStorage. App.tsx routes start screen <-> game (code-split the game chunk with React.lazy); keep ?test=1/?scenario/?gallery/?fps hooks.` },
]
const parts = await parallel(PARTS.map(p => () => agent(`${COMMON}
Read src/client/contract.ts first (frozen; if you need something missing, add a local adapter in your own files and note it in issues). Task: ${p.task}
You own ONLY: ${p.own}, plus tests/client/${p.key}*.test.ts. Run typecheck (ignore errors in files you don't own, report them) and your tests.
Return JSON: ok, summary (<=80 words), files, issues.`, { label: `client:${p.key}`, phase: 'Build', schema: RESULT, model: 'sonnet' })))

phase('Ship')
const ship = await agent(`${COMMON}
Integrate and ship the playable slice. You may edit any file under src/client, tests, playwright config, package.json (npm install allowed), STATUS.md, HANDOFF.md; minimal src/engine fixes only if the client is blocked (mirror contract changes in docs/spec/00-architecture.md §14).
1. npm run typecheck, npm test, npm run build green. Run 'npx playwright install chromium' once if needed.
2. PLAY it yourself in Playwright (PW_PORT=4183): start the intro mission vs the bot, move with walk/run/jump and facing, torso twist, fire weapons, watch heat, kick when adjacent, play until a 'Mech is destroyed or turn 4; fix every crash, stuck state, invisible prompt, unexplained number or unreadable panel. The human must always see what to do next.
3. tests/e2e/play.spec.ts: start screen -> How to Play (assert tabs) -> start -> the human plays turns through the real UI (clicks; window.__game only to read state or fast-forward) until game over or turn 4; screenshots to e2e-out/: start.png, howto.png, move.png, fire-prompt.png, record-sheet.png, midgame.png, end.png. Read the screenshots and fix what looks broken.
4. Main chunk < 1 MB (code-split start screen vs game vs AI).
5. Update STATUS.md and HANDOFF.md (next: owner playtest, M3 figure gate, M4 AI). Also stage public/assets/models/*.glb + manifest.json, art/unit-concepts/*.png and art/figure-sheets/*.png (our generated figures). Stage by exact path (never e2e-out, test-results, tools/out, docs/sources, PDFs, tokens); commit "M3: playable vertical slice vs random bot" + blank line + "${ATTR}"; git pull --rebase; git push origin main; gh run watch the deploy with --exit-status (fix and retry up to 2 times); then curl -s https://dragoonant.github.io/warmechforge/ | grep -i warmechforge.
Return JSON: ok, summary (<=120 words: what a player can do, known gaps), files (include absolute screenshot paths), issues.`, { label: 'ship', phase: 'Ship', schema: RESULT, effort: 'high' })

const s = r => r && { ok: r.ok, summary: r.summary, files: r.files.slice(0, 10), issues: r.issues.slice(0, 8) }
return { core: s(core), parts: parts.map(s), ship: s(ship) }
